logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
excluded-patches = "'Vanced MicroG support' 'Copy video url' 'Swipe controls' 'Disable fine scrubbing gesture' 'Enable tablet layout' 'Hide info cards' 'Hide timestamp' 'Comments' 'Hide seekbar' 'Hide layout components' 'Player flyout menu' 'Hide 'Load more' button' 'Wide searchbar' 'Tablet mini player' 'Spoof app version' 'Theme' 'Hide captions button' 'Hide autoplay button' 'Disable player popup panels'"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Permanent repeat' 'Permanent shuffle'"
excluded-patches = "'Vanced MicroG support'"

[Lightroom]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/adobe/lightroom/"
apkmirror-arch = "arm64-v8a + x86_64"

[IconPackStudio]
enabled = true
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[Photomath]
enabled = true
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"
